baseurl = "https://www.pbjorklund.com"
title = "I Might Be Wrong"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "pbjorklund"

[markup.highlight]
style = "github-dark"

[params]
  author = "Patrik Bj√∂rklund"
  info = "Father, Business, Product, AI, Marketing, Running"
  description = "Patriks thoughts"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/pbjorklund/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/pbjorklund"
[[params.social]]
  name = "Email"
  icon = "fas fa-envelope fa-2x"
  weight = 3
  url = "mailto:p.bjorklund@gmail.com?subject=Hello!&body=How%20are%20you?"
[[params.social]]
  name = "Email"
  icon = "fab fa-strava fa-2x"
  weight = 3
  url = "https://www.strava.com/athletes/45718367"

# Menu links
[[menu.main]]
  name = "AmpliFlow (SE)"
  weight = 1
  url  = "https://www.ampliflow.se"
[[menu.main]]
  name = "AmpliFlow (EN)"
  weight = 2
  url  = "https://www.ampliflow.com"
[[menu.main]]
  name = "Cognit"
  weight = 3
  url  = "https://www.cognit.se"
[[menu.main]]
  name = "Blog"
  weight = 4
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 5
  url = "about/"